-- FM Lite seed data (generated by tools/generate-seed.mjs, seed=20260711)
-- 팀 8개 / 팀당 18명 (GK2 DF6 MF6 FW4)

insert into teams (name, short_name, grade, description) values ('레드 스톰 FC', 'RSF', 'STRONG', '화력 중심의 최강팀. 공격 앞에 장사 없다.');
insert into teams (name, short_name, grade, description) values ('블루 나이츠', 'BLK', 'STRONG', '철벽 수비의 강호. 실점이 곧 뉴스가 되는 팀.');
insert into teams (name, short_name, grade, description) values ('골든 이글스', 'GDE', 'UPPER_MID', '번개 같은 역습. 한 방이 있는 팀.');
insert into teams (name, short_name, grade, description) values ('실버 울브스', 'SVW', 'UPPER_MID', '중원 장악의 명수. 점유율로 상대를 질식시킨다.');
insert into teams (name, short_name, grade, description) values ('그린 파이터스', 'GRF', 'MID', '공수 균형이 잡힌 전형적인 토너먼트형 팀.');
insert into teams (name, short_name, grade, description) values ('오렌지 웨이브', 'ORW', 'MID', '측면 돌파와 크로스가 주무기인 팀.');
insert into teams (name, short_name, grade, description) values ('퍼플 가디언스', 'PPG', 'WEAK', '수비 일변도. 버티고 버텨 승부차기를 노린다.');
insert into teams (name, short_name, grade, description) values ('화이트 폭스', 'WFX', 'WEAK', '패기 넘치는 도전자. 이변의 주인공을 꿈꾼다.');

insert into players (team_id, name, position, back_number, attack, defense, passing, speed, stamina, mentality, finishing, goalkeeping, traits)
select t.id, v.* from (values
  ('조규민', 'GK', 1, 62, 77, 76, 81, 82, 85, 56, 92, '{}'::text[]),
  ('임지호', 'GK', 21, 53, 80, 81, 75, 76, 81, 56, 87, array['PK_SAVER','WEAK_UNDER_PRESSURE']),
  ('이민준', 'DF', 2, 73, 84, 74, 73, 77, 75, 63, 13, array['POOR_CONCENTRATION','AERIAL_THREAT']),
  ('차우진', 'DF', 3, 78, 80, 72, 73, 83, 78, 67, 10, array['AERIAL_THREAT','BIG_GAME_PLAYER']),
  ('남정우', 'DF', 4, 75, 83, 81, 83, 78, 77, 71, 14, '{}'::text[]),
  ('진해성', 'DF', 5, 80, 84, 82, 82, 75, 81, 62, 15, '{}'::text[]),
  ('홍강민', 'DF', 15, 78, 84, 73, 75, 73, 82, 68, 7, '{}'::text[]),
  ('배수호', 'DF', 22, 74, 88, 84, 74, 72, 86, 63, 10, array['BIG_GAME_PLAYER']),
  ('신도윤', 'MF', 6, 84, 72, 84, 75, 82, 79, 79, 20, array['PASS_MASTER']),
  ('권지호', 'MF', 7, 77, 77, 87, 77, 79, 83, 81, 11, '{}'::text[]),
  ('문시윤', 'MF', 8, 77, 83, 80, 72, 85, 78, 82, 11, '{}'::text[]),
  ('박도윤', 'MF', 10, 74, 79, 91, 78, 86, 80, 75, 17, '{}'::text[]),
  ('민규민', 'MF', 14, 78, 74, 81, 74, 79, 75, 78, 20, array['BIG_GAME_PLAYER','WEAK_UNDER_PRESSURE']),
  ('임민재', 'MF', 16, 80, 82, 91, 72, 79, 84, 72, 15, '{}'::text[]),
  ('민승현', 'FW', 9, 87, 64, 78, 79, 77, 77, 91, 18, '{}'::text[]),
  ('강동현', 'FW', 11, 86, 63, 77, 80, 77, 77, 90, 16, '{}'::text[]),
  ('윤지훈', 'FW', 17, 86, 71, 76, 81, 81, 78, 84, 12, '{}'::text[]),
  ('황연우', 'FW', 19, 83, 68, 82, 83, 76, 82, 90, 9, '{}'::text[])
) as v(name, position, back_number, attack, defense, passing, speed, stamina, mentality, finishing, goalkeeping, traits)
cross join (select id from teams where name = '레드 스톰 FC') t;

insert into players (team_id, name, position, back_number, attack, defense, passing, speed, stamina, mentality, finishing, goalkeeping, traits)
select t.id, v.* from (values
  ('오현우', 'GK', 1, 60, 78, 77, 77, 72, 86, 64, 84, '{}'::text[]),
  ('안성민', 'GK', 21, 64, 81, 81, 75, 74, 78, 53, 88, array['WEAK_UNDER_PRESSURE']),
  ('오준서', 'DF', 2, 80, 87, 76, 83, 72, 84, 69, 6, array['POOR_CONCENTRATION']),
  ('최강찬', 'DF', 3, 77, 87, 74, 75, 79, 78, 66, 10, '{}'::text[]),
  ('진강민', 'DF', 4, 82, 82, 78, 84, 84, 83, 72, 7, array['WEAK_UNDER_PRESSURE']),
  ('오준혁', 'DF', 5, 82, 86, 75, 74, 80, 81, 71, 17, '{}'::text[]),
  ('문태윤', 'DF', 15, 84, 90, 73, 81, 82, 75, 74, 15, '{}'::text[]),
  ('주세준', 'DF', 22, 73, 85, 79, 79, 84, 87, 64, 16, array['LOW_STAMINA']),
  ('남재현', 'MF', 6, 76, 75, 91, 81, 87, 73, 78, 20, '{}'::text[]),
  ('황우진', 'MF', 7, 80, 76, 92, 74, 80, 72, 72, 8, '{}'::text[]),
  ('류현우', 'MF', 8, 75, 74, 86, 78, 80, 83, 73, 19, array['WEAK_UNDER_PRESSURE']),
  ('우지호', 'MF', 10, 82, 72, 83, 84, 86, 72, 80, 10, '{}'::text[]),
  ('송동현', 'MF', 14, 74, 83, 84, 78, 82, 76, 83, 5, array['LONG_SHOT']),
  ('황서준', 'MF', 16, 74, 75, 89, 74, 75, 75, 81, 5, array['LONG_SHOT']),
  ('권정우', 'FW', 9, 91, 67, 74, 86, 80, 76, 89, 5, array['LONG_SHOT','AERIAL_THREAT']),
  ('배선우', 'FW', 11, 85, 74, 84, 83, 82, 77, 88, 13, '{}'::text[]),
  ('이우진', 'FW', 17, 82, 69, 83, 77, 75, 84, 83, 7, array['LONG_SHOT']),
  ('윤시우', 'FW', 19, 83, 64, 82, 85, 77, 74, 83, 16, array['LONG_SHOT','RUN_IN_BEHIND'])
) as v(name, position, back_number, attack, defense, passing, speed, stamina, mentality, finishing, goalkeeping, traits)
cross join (select id from teams where name = '블루 나이츠') t;

insert into players (team_id, name, position, back_number, attack, defense, passing, speed, stamina, mentality, finishing, goalkeeping, traits)
select t.id, v.* from (values
  ('문윤호', 'GK', 1, 51, 74, 78, 66, 67, 69, 53, 78, array['BIG_GAME_PLAYER']),
  ('임재현', 'GK', 21, 49, 66, 70, 72, 69, 74, 50, 88, '{}'::text[]),
  ('송태양', 'DF', 2, 68, 84, 73, 73, 77, 69, 57, 11, array['AERIAL_THREAT']),
  ('남서준', 'DF', 3, 78, 86, 75, 73, 67, 79, 56, 6, array['POOR_CONCENTRATION','AERIAL_THREAT']),
  ('우주원', 'DF', 4, 76, 78, 66, 75, 69, 78, 57, 6, array['AERIAL_THREAT']),
  ('강승현', 'DF', 5, 72, 78, 78, 69, 74, 75, 58, 19, array['BIG_GAME_PLAYER']),
  ('권승우', 'DF', 15, 66, 80, 73, 78, 75, 70, 67, 9, array['BIG_GAME_PLAYER']),
  ('최도현', 'DF', 22, 78, 78, 70, 67, 72, 72, 67, 15, '{}'::text[]),
  ('한현우', 'MF', 6, 66, 75, 75, 76, 79, 74, 66, 10, '{}'::text[]),
  ('임시우', 'MF', 7, 75, 71, 85, 67, 78, 66, 67, 20, '{}'::text[]),
  ('백민재', 'MF', 8, 78, 75, 76, 66, 80, 78, 72, 18, array['WEAK_UNDER_PRESSURE','BIG_GAME_PLAYER']),
  ('한도현', 'MF', 10, 69, 78, 76, 72, 70, 74, 78, 9, '{}'::text[]),
  ('오태양', 'MF', 14, 75, 73, 84, 68, 73, 74, 71, 18, array['LOW_STAMINA']),
  ('정태양', 'MF', 16, 75, 73, 84, 67, 75, 70, 75, 19, '{}'::text[]),
  ('오도현', 'FW', 9, 79, 65, 74, 70, 73, 77, 74, 19, '{}'::text[]),
  ('최준혁', 'FW', 11, 81, 62, 67, 76, 67, 76, 78, 15, array['BIG_GAME_PLAYER']),
  ('홍정우', 'FW', 17, 86, 63, 77, 79, 66, 66, 79, 11, '{}'::text[]),
  ('문성민', 'FW', 19, 75, 59, 68, 77, 70, 72, 77, 17, '{}'::text[])
) as v(name, position, back_number, attack, defense, passing, speed, stamina, mentality, finishing, goalkeeping, traits)
cross join (select id from teams where name = '골든 이글스') t;

insert into players (team_id, name, position, back_number, attack, defense, passing, speed, stamina, mentality, finishing, goalkeeping, traits)
select t.id, v.* from (values
  ('정하준', 'GK', 1, 48, 76, 72, 69, 68, 72, 56, 83, array['BIG_GAME_PLAYER']),
  ('주현우', 'GK', 21, 47, 68, 67, 72, 67, 78, 58, 89, '{}'::text[]),
  ('김동현', 'DF', 2, 78, 80, 66, 72, 76, 72, 60, 16, '{}'::text[]),
  ('백재현', 'DF', 3, 69, 77, 70, 71, 77, 71, 64, 13, array['WEAK_UNDER_PRESSURE','LOW_STAMINA']),
  ('서도현', 'DF', 4, 77, 74, 73, 70, 76, 73, 57, 5, '{}'::text[]),
  ('오서준', 'DF', 5, 69, 83, 74, 78, 69, 73, 62, 7, '{}'::text[]),
  ('한연우', 'DF', 15, 75, 84, 77, 72, 77, 78, 67, 18, '{}'::text[]),
  ('권유준', 'DF', 22, 66, 78, 75, 72, 76, 78, 62, 6, array['AERIAL_THREAT']),
  ('정서준', 'MF', 6, 76, 67, 82, 66, 76, 76, 78, 8, array['LOW_STAMINA']),
  ('홍규민', 'MF', 7, 78, 70, 76, 69, 69, 74, 75, 16, array['LOW_STAMINA']),
  ('홍하준', 'MF', 8, 77, 68, 79, 71, 80, 74, 78, 9, '{}'::text[]),
  ('문건우', 'MF', 10, 77, 71, 79, 70, 81, 69, 70, 10, '{}'::text[]),
  ('신재현', 'MF', 14, 77, 76, 78, 70, 69, 75, 77, 14, '{}'::text[]),
  ('임정우', 'MF', 16, 68, 68, 84, 75, 69, 72, 77, 6, array['BIG_GAME_PLAYER']),
  ('안강민', 'FW', 9, 76, 57, 76, 78, 67, 78, 81, 8, array['BIG_GAME_PLAYER']),
  ('권윤호', 'FW', 11, 75, 59, 69, 80, 72, 74, 80, 16, '{}'::text[]),
  ('강우진', 'FW', 17, 74, 65, 75, 77, 77, 73, 75, 11, array['BIG_GAME_PLAYER']),
  ('조유준', 'FW', 19, 83, 56, 76, 78, 72, 77, 80, 8, '{}'::text[])
) as v(name, position, back_number, attack, defense, passing, speed, stamina, mentality, finishing, goalkeeping, traits)
cross join (select id from teams where name = '실버 울브스') t;

insert into players (team_id, name, position, back_number, attack, defense, passing, speed, stamina, mentality, finishing, goalkeeping, traits)
select t.id, v.* from (values
  ('강강민', 'GK', 1, 50, 65, 70, 60, 66, 68, 40, 80, '{}'::text[]),
  ('김연우', 'GK', 21, 52, 69, 70, 65, 72, 73, 43, 75, array['BIG_GAME_PLAYER']),
  ('서해성', 'DF', 2, 61, 71, 61, 60, 67, 74, 59, 20, array['BIG_GAME_PLAYER','LOW_STAMINA']),
  ('안동현', 'DF', 3, 60, 71, 70, 70, 71, 64, 61, 16, array['AERIAL_THREAT']),
  ('안은우', 'DF', 4, 70, 71, 70, 69, 66, 73, 54, 17, array['BIG_GAME_PLAYER']),
  ('주민재', 'DF', 5, 62, 70, 62, 66, 67, 74, 54, 13, array['POOR_CONCENTRATION']),
  ('조하준', 'DF', 15, 61, 74, 63, 71, 64, 69, 54, 17, '{}'::text[]),
  ('한민준', 'DF', 22, 64, 74, 67, 69, 68, 66, 60, 15, '{}'::text[]),
  ('임태양', 'MF', 6, 61, 62, 75, 61, 73, 60, 70, 7, array['WEAK_UNDER_PRESSURE']),
  ('민연우', 'MF', 7, 62, 62, 69, 64, 69, 69, 68, 15, array['BIG_GAME_PLAYER']),
  ('황준서', 'MF', 8, 68, 63, 80, 61, 72, 66, 70, 7, array['LOW_STAMINA']),
  ('홍시윤', 'MF', 10, 61, 64, 74, 64, 63, 67, 72, 11, array['PASS_MASTER','WEAK_UNDER_PRESSURE']),
  ('남지환', 'MF', 14, 64, 60, 78, 60, 70, 65, 72, 20, '{}'::text[]),
  ('민현우', 'MF', 16, 67, 72, 77, 71, 70, 65, 72, 15, array['PASS_MASTER']),
  ('송해성', 'FW', 9, 75, 57, 62, 63, 66, 62, 74, 13, '{}'::text[]),
  ('주승우', 'FW', 11, 77, 62, 66, 73, 60, 72, 75, 17, array['LONG_SHOT']),
  ('최지환', 'FW', 17, 69, 55, 61, 65, 65, 66, 75, 19, array['AERIAL_THREAT','BIG_GAME_PLAYER']),
  ('한시윤', 'FW', 19, 69, 51, 69, 74, 69, 71, 73, 8, '{}'::text[])
) as v(name, position, back_number, attack, defense, passing, speed, stamina, mentality, finishing, goalkeeping, traits)
cross join (select id from teams where name = '그린 파이터스') t;

insert into players (team_id, name, position, back_number, attack, defense, passing, speed, stamina, mentality, finishing, goalkeeping, traits)
select t.id, v.* from (values
  ('남동현', 'GK', 1, 43, 67, 61, 71, 60, 75, 41, 83, array['PK_SAVER']),
  ('안유준', 'GK', 21, 46, 69, 65, 69, 65, 72, 48, 84, array['PK_SAVER','BIG_GAME_PLAYER']),
  ('최시윤', 'DF', 2, 62, 76, 60, 66, 67, 65, 54, 11, array['WEAK_UNDER_PRESSURE']),
  ('권우진', 'DF', 3, 63, 77, 64, 72, 67, 64, 52, 16, '{}'::text[]),
  ('권태양', 'DF', 4, 63, 72, 65, 61, 64, 64, 59, 15, array['WEAK_UNDER_PRESSURE']),
  ('우도현', 'DF', 5, 65, 79, 60, 66, 71, 73, 54, 16, array['AERIAL_THREAT']),
  ('최주원', 'DF', 15, 70, 75, 71, 72, 70, 65, 61, 6, array['AERIAL_THREAT']),
  ('박지훈', 'DF', 22, 69, 75, 62, 64, 61, 64, 50, 5, array['LOW_STAMINA']),
  ('민수호', 'MF', 6, 67, 66, 73, 65, 73, 60, 66, 14, array['BIG_GAME_PLAYER']),
  ('안재윤', 'MF', 7, 60, 71, 72, 60, 69, 71, 63, 19, array['LONG_SHOT']),
  ('강유준', 'MF', 8, 71, 63, 79, 65, 73, 64, 66, 17, array['BIG_GAME_PLAYER']),
  ('안태민', 'MF', 10, 61, 61, 68, 64, 69, 65, 71, 16, array['LONG_SHOT']),
  ('우성민', 'MF', 14, 61, 71, 75, 64, 65, 62, 72, 8, array['PASS_MASTER','LONG_SHOT']),
  ('차연우', 'MF', 16, 66, 70, 80, 71, 75, 71, 70, 6, array['LOW_STAMINA','WEAK_UNDER_PRESSURE']),
  ('조민성', 'FW', 9, 70, 62, 62, 69, 71, 69, 75, 12, '{}'::text[]),
  ('윤규민', 'FW', 11, 79, 52, 62, 75, 68, 60, 80, 20, '{}'::text[]),
  ('임강찬', 'FW', 17, 79, 57, 70, 68, 70, 69, 76, 19, array['AERIAL_THREAT']),
  ('문승현', 'FW', 19, 76, 53, 61, 66, 69, 65, 77, 6, array['AERIAL_THREAT'])
) as v(name, position, back_number, attack, defense, passing, speed, stamina, mentality, finishing, goalkeeping, traits)
cross join (select id from teams where name = '오렌지 웨이브') t;

insert into players (team_id, name, position, back_number, attack, defense, passing, speed, stamina, mentality, finishing, goalkeeping, traits)
select t.id, v.* from (values
  ('안도현', 'GK', 1, 43, 60, 64, 57, 63, 64, 39, 68, array['BIG_GAME_PLAYER']),
  ('진윤호', 'GK', 21, 41, 62, 54, 63, 60, 58, 34, 73, '{}'::text[]),
  ('류서준', 'DF', 2, 60, 73, 55, 59, 62, 69, 55, 6, array['AERIAL_THREAT']),
  ('황태양', 'DF', 3, 66, 65, 63, 63, 56, 65, 46, 17, array['POOR_CONCENTRATION']),
  ('배은우', 'DF', 4, 61, 65, 65, 63, 56, 57, 56, 18, '{}'::text[]),
  ('황주원', 'DF', 5, 66, 72, 59, 64, 66, 61, 56, 12, array['WEAK_UNDER_PRESSURE','BIG_GAME_PLAYER']),
  ('차지환', 'DF', 15, 59, 69, 56, 58, 60, 68, 52, 11, array['WEAK_UNDER_PRESSURE']),
  ('이민재', 'DF', 22, 58, 66, 56, 66, 66, 64, 54, 14, array['BIG_GAME_PLAYER']),
  ('정정우', 'MF', 6, 64, 55, 73, 63, 62, 59, 57, 13, '{}'::text[]),
  ('오지호', 'MF', 7, 59, 55, 67, 62, 58, 66, 54, 19, array['PASS_MASTER','WEAK_UNDER_PRESSURE']),
  ('박우진', 'MF', 8, 62, 61, 71, 66, 66, 66, 58, 12, array['BIG_GAME_PLAYER']),
  ('박승현', 'MF', 10, 56, 65, 69, 54, 67, 57, 62, 14, array['LONG_SHOT','BIG_GAME_PLAYER']),
  ('주서준', 'MF', 14, 58, 65, 63, 64, 68, 66, 60, 11, '{}'::text[]),
  ('백한결', 'MF', 16, 60, 54, 68, 54, 60, 64, 57, 17, array['LONG_SHOT']),
  ('우서준', 'FW', 9, 69, 56, 56, 68, 60, 66, 68, 11, '{}'::text[]),
  ('안태양', 'FW', 11, 71, 53, 54, 66, 66, 66, 71, 6, array['RUN_IN_BEHIND']),
  ('임규민', 'FW', 17, 67, 52, 54, 62, 60, 61, 66, 7, array['LONG_SHOT']),
  ('차태민', 'FW', 19, 69, 48, 54, 60, 63, 58, 62, 17, array['LONG_SHOT'])
) as v(name, position, back_number, attack, defense, passing, speed, stamina, mentality, finishing, goalkeeping, traits)
cross join (select id from teams where name = '퍼플 가디언스') t;

insert into players (team_id, name, position, back_number, attack, defense, passing, speed, stamina, mentality, finishing, goalkeeping, traits)
select t.id, v.* from (values
  ('우규민', 'GK', 1, 43, 56, 58, 55, 60, 58, 42, 77, '{}'::text[]),
  ('남도윤', 'GK', 21, 36, 64, 57, 60, 66, 63, 41, 72, '{}'::text[]),
  ('한은우', 'DF', 2, 65, 62, 57, 60, 60, 60, 45, 15, '{}'::text[]),
  ('윤민재', 'DF', 3, 63, 68, 55, 62, 54, 68, 51, 9, '{}'::text[]),
  ('차주원', 'DF', 4, 56, 68, 58, 62, 62, 62, 44, 6, array['WEAK_UNDER_PRESSURE']),
  ('남준혁', 'DF', 5, 55, 72, 60, 61, 59, 60, 52, 13, array['BIG_GAME_PLAYER','LOW_STAMINA']),
  ('박정우', 'DF', 15, 66, 72, 54, 54, 55, 64, 55, 6, '{}'::text[]),
  ('김지환', 'DF', 22, 65, 66, 61, 66, 65, 67, 46, 12, '{}'::text[]),
  ('신지훈', 'MF', 6, 64, 64, 69, 63, 58, 62, 62, 18, '{}'::text[]),
  ('조승현', 'MF', 7, 63, 66, 69, 63, 68, 58, 60, 7, '{}'::text[]),
  ('문도윤', 'MF', 8, 54, 57, 74, 57, 68, 54, 66, 15, array['WEAK_UNDER_PRESSURE','LOW_STAMINA']),
  ('문하준', 'MF', 10, 62, 65, 65, 56, 58, 65, 61, 18, array['LONG_SHOT']),
  ('강성민', 'MF', 14, 63, 58, 65, 64, 62, 54, 54, 16, '{}'::text[]),
  ('박민준', 'MF', 16, 61, 56, 66, 60, 58, 63, 63, 8, '{}'::text[]),
  ('최승현', 'FW', 9, 65, 48, 57, 67, 54, 63, 71, 7, '{}'::text[]),
  ('차시윤', 'FW', 11, 67, 44, 57, 63, 55, 54, 65, 12, array['LONG_SHOT']),
  ('안정우', 'FW', 17, 68, 52, 54, 57, 65, 62, 74, 14, '{}'::text[]),
  ('이태윤', 'FW', 19, 69, 50, 63, 64, 54, 65, 73, 13, '{}'::text[])
) as v(name, position, back_number, attack, defense, passing, speed, stamina, mentality, finishing, goalkeeping, traits)
cross join (select id from teams where name = '화이트 폭스') t;

