// FM Lite seed generator — 결정적(seeded) 랜덤으로 8팀 × 18명 선수 시드 SQL 생성
// 실행: node tools/generate-seed.mjs > backend/src/main/resources/db/migration/V2__seed.sql
// 같은 시드면 항상 같은 결과가 나오므로, 생성 결과를 커밋해 고정한다.

const SEED = 20260711;

// mulberry32 PRNG
function mulberry32(a) {
  return function () {
    a |= 0; a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
const rand = mulberry32(SEED);
const randInt = (min, max) => Math.floor(rand() * (max - min + 1)) + min;
const pick = (arr) => arr[Math.floor(rand() * arr.length)];
const clamp = (v, lo, hi) => Math.max(lo, Math.min(hi, v));

const TEAMS = [
  { name: '레드 스톰 FC', short: 'RSF', grade: 'STRONG',    desc: '화력 중심의 최강팀. 공격 앞에 장사 없다.' },
  { name: '블루 나이츠',  short: 'BLK', grade: 'STRONG',    desc: '철벽 수비의 강호. 실점이 곧 뉴스가 되는 팀.' },
  { name: '골든 이글스',  short: 'GDE', grade: 'UPPER_MID', desc: '번개 같은 역습. 한 방이 있는 팀.' },
  { name: '실버 울브스',  short: 'SVW', grade: 'UPPER_MID', desc: '중원 장악의 명수. 점유율로 상대를 질식시킨다.' },
  { name: '그린 파이터스', short: 'GRF', grade: 'MID',       desc: '공수 균형이 잡힌 전형적인 토너먼트형 팀.' },
  { name: '오렌지 웨이브', short: 'ORW', grade: 'MID',       desc: '측면 돌파와 크로스가 주무기인 팀.' },
  { name: '퍼플 가디언스', short: 'PPG', grade: 'WEAK',      desc: '수비 일변도. 버티고 버텨 승부차기를 노린다.' },
  { name: '화이트 폭스',  short: 'WFX', grade: 'WEAK',      desc: '패기 넘치는 도전자. 이변의 주인공을 꿈꾼다.' },
];

const GRADE_BASE = { STRONG: 78, UPPER_MID: 72, MID: 66, WEAK: 60 };

// 포지션 구성: GK2 DF6 MF6 FW4, 등번호 고정 풀
const SQUAD_PLAN = [
  { pos: 'GK', numbers: [1, 21] },
  { pos: 'DF', numbers: [2, 3, 4, 5, 15, 22] },
  { pos: 'MF', numbers: [6, 7, 8, 10, 14, 16] },
  { pos: 'FW', numbers: [9, 11, 17, 19] },
];

const SURNAMES = ['김', '이', '박', '최', '정', '강', '조', '윤', '장', '임', '한', '오', '서', '신', '권', '황', '안', '송', '류', '홍', '문', '배', '백', '남', '차', '주', '우', '구', '민', '진'];
const GIVEN = ['민준', '서준', '도윤', '시우', '주원', '하준', '지호', '준서', '건우', '현우', '우진', '선우', '연우', '정우', '승우', '지훈', '태윤', '은우', '수호', '유준', '재윤', '시윤', '동현', '민재', '성민', '재현', '태민', '규민', '한결', '승현', '강찬', '도현', '지환', '세준', '민성', '준혁', '윤호', '태양', '해성', '강민'];

const TRAIT_POOL = {
  GK: ['PK_SAVER', 'BIG_GAME_PLAYER', 'WEAK_UNDER_PRESSURE'],
  DF: ['AERIAL_THREAT', 'POOR_CONCENTRATION', 'BIG_GAME_PLAYER', 'LOW_STAMINA', 'WEAK_UNDER_PRESSURE'],
  MF: ['PASS_MASTER', 'LONG_SHOT', 'LOW_STAMINA', 'BIG_GAME_PLAYER', 'WEAK_UNDER_PRESSURE'],
  FW: ['RUN_IN_BEHIND', 'AERIAL_THREAT', 'LONG_SHOT', 'BIG_GAME_PLAYER', 'LOW_STAMINA'],
};

const usedNames = new Set();
function uniqueName() {
  for (let i = 0; i < 1000; i++) {
    const n = pick(SURNAMES) + pick(GIVEN);
    if (!usedNames.has(n)) { usedNames.add(n); return n; }
  }
  throw new Error('name pool exhausted');
}

function statsFor(pos, base) {
  const d = () => randInt(-6, 6);
  const s = {
    attack: base + d(), defense: base + d(), passing: base + d(), speed: base + d(),
    stamina: base + d(), mentality: base + d(), finishing: base + d(), goalkeeping: randInt(5, 20),
  };
  if (pos === 'GK') {
    s.goalkeeping = base + 12 + d(); s.mentality += 3; s.attack -= 20; s.finishing -= 20;
  } else if (pos === 'DF') {
    s.defense += 8; s.mentality += 3; s.finishing -= 10;
  } else if (pos === 'MF') {
    s.passing += 8; s.stamina += 3;
  } else if (pos === 'FW') {
    s.finishing += 8; s.attack += 8; s.speed += 3; s.defense -= 10;
  }
  for (const k of Object.keys(s)) s[k] = clamp(s[k], 1, 99);
  return s;
}

function traitsFor(pos) {
  const r = rand();
  const pool = [...TRAIT_POOL[pos]];
  const result = [];
  const take = () => result.push(pool.splice(Math.floor(rand() * pool.length), 1)[0]);
  if (r < 0.15) { take(); take(); }
  else if (r < 0.55) { take(); }
  return result;
}

const esc = (s) => s.replace(/'/g, "''");
let out = [];
out.push('-- FM Lite seed data (generated by tools/generate-seed.mjs, seed=' + SEED + ')');
out.push('-- 팀 8개 / 팀당 18명 (GK2 DF6 MF6 FW4)');
out.push('');

for (const t of TEAMS) {
  out.push(`insert into teams (name, short_name, grade, description) values ('${esc(t.name)}', '${t.short}', '${t.grade}', '${esc(t.desc)}');`);
}
out.push('');

for (const t of TEAMS) {
  const base = GRADE_BASE[t.grade];
  const rows = [];
  for (const plan of SQUAD_PLAN) {
    for (const num of plan.numbers) {
      const name = uniqueName();
      const s = statsFor(plan.pos, base);
      const traits = traitsFor(plan.pos);
      const traitSql = traits.length ? `array['${traits.join("','")}']` : `'{}'::text[]`;
      rows.push(`  ('${esc(name)}', '${plan.pos}', ${num}, ${s.attack}, ${s.defense}, ${s.passing}, ${s.speed}, ${s.stamina}, ${s.mentality}, ${s.finishing}, ${s.goalkeeping}, ${traitSql})`);
    }
  }
  out.push(`insert into players (team_id, name, position, back_number, attack, defense, passing, speed, stamina, mentality, finishing, goalkeeping, traits)`);
  out.push(`select t.id, v.* from (values`);
  out.push(rows.join(',\n'));
  out.push(`) as v(name, position, back_number, attack, defense, passing, speed, stamina, mentality, finishing, goalkeeping, traits)`);
  out.push(`cross join (select id from teams where name = '${esc(t.name)}') t;`);
  out.push('');
}

console.log(out.join('\n'));
